#!/usr/bin/env python3
"""
Which of these errors name something this project claims to own.

The checker's output is long and almost entirely androidx noise, and that is
precisely how a real error hides in it: `SurfaceVariantDark` was never defined
anywhere, sat in a list of 223 "unresolved reference" lines, and reached a
release build because the list got skimmed and the whole category was waved
through as invisible-androidx.

One rule, because one rule is what can be relied on:

    a file that writes `import com.animeh.….Name` and then cannot resolve
    `Name` is wrong, and no missing jar can explain it.

That import is the file stating we ship the symbol. If the compiler disagrees,
it does not exist — which is the shape of every colour, helper and constant
invented by hand and never declared. Anything else stays in the long list where
it belongs; being quiet about the rest is what keeps this short enough to read.

Reads error lines on stdin, writes back only the ones that break that rule.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

UNRESOLVED = re.compile(r"unresolved reference '([^']+)'")
LINE = re.compile(r"^\s*(\S+\.kt)\s+(.*)$")

# `com.animeh.app.R` is ours by package and generated by aapt, so it is absent
# from every compile here and every screen that imports it would be listed.
# It has its own check: android_resources.py reads res/ directly and verifies
# each R.string / R.drawable use against it.
GENERATED = {"R"}


def ours(path: Path) -> set[str]:
    """Names a file imports by name from one of our own packages."""
    if not path.is_file():
        return set()

    found: set[str] = set()

    for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
        if not line.startswith("import com.animeh."):
            continue
        # A wildcard names nothing in particular, so it proves nothing.
        if line.rstrip().endswith("*"):
            continue

        found.add(line.rstrip().rsplit(".", 1)[-1])

    return found


def main() -> int:
    root = Path(sys.argv[1]) if len(sys.argv) > 1 else Path("android")
    cache: dict[str, set[str]] = {}

    for raw in sys.stdin:
        error = raw.rstrip("\n")

        symbol = UNRESOLVED.search(error)
        parsed = LINE.match(error)
        if not symbol or not parsed:
            continue

        relative = parsed.group(1)
        if relative not in cache:
            cache[relative] = ours(root / relative)

        name = symbol.group(1)
        if name not in GENERATED and name in cache[relative]:
            print(error)

    return 0


if __name__ == "__main__":
    sys.exit(main())
