#!/usr/bin/env python3
"""Does every R.<type>.<name> in the Kotlin sources actually exist?

`R` is generated by aapt from res/, so the compiler here cannot see it: with
no Android classpath, `R` is unresolved and everything under it is invisible.
That is how `R.string.add_to_list` — a name I invented — reached a release
build and failed it.

The answer does not need a compiler. The names live in res/values/*.xml and in
the file names under res/drawable, res/layout and the rest, and this compares
the two sets directly.
"""

import re
import sys
import pathlib
import xml.etree.ElementTree as ET

# <string name="x">, <color name="x">, <dimen name="x">, <style name="x">…
VALUE_TAGS = {
    "string": "string",
    "string-array": "array",
    "integer-array": "array",
    "plurals": "plurals",
    "color": "color",
    "dimen": "dimen",
    "bool": "bool",
    "integer": "integer",
    "style": "style",
    "attr": "attr",
    "item": None,  # carries its own `type` attribute
}

# res/<dir>/<name>.<ext> declares R.<dir>.<name>
FILE_DIRS = {
    "drawable": "drawable",
    "mipmap": "mipmap",
    "layout": "layout",
    "menu": "menu",
    "anim": "anim",
    "animator": "animator",
    "raw": "raw",
    "font": "font",
    "xml": "xml",
    "color": "color",
}


def declared(res_root: pathlib.Path) -> set[tuple[str, str]]:
    names: set[tuple[str, str]] = set()

    for xml_file in res_root.glob("values*/*.xml"):
        try:
            tree = ET.parse(xml_file)
        except ET.ParseError as error:
            print(f"{xml_file}: okunamadı — {error}", file=sys.stderr)
            continue

        for element in tree.getroot():
            name = element.get("name")
            if not name:
                continue

            kind = VALUE_TAGS.get(element.tag, "__unknown__")
            if kind is None:
                kind = element.get("type") or "__unknown__"
            if kind == "__unknown__":
                continue

            # A dotted style name is R.style.Theme_Animeh.
            names.add((kind, name.replace(".", "_")))

    for directory in res_root.iterdir():
        if not directory.is_dir():
            continue

        # `drawable-night`, `mipmap-hdpi`, `values-tr` all fold into one name.
        kind = FILE_DIRS.get(directory.name.split("-")[0])
        if kind is None:
            continue

        for asset in directory.iterdir():
            if asset.is_file():
                names.add((kind, asset.name.split(".")[0]))

    return names


def used(source_root: pathlib.Path) -> list[tuple[str, str, str, int]]:
    # `R.string.foo` and `android.R.string.ok` — the second is not ours.
    pattern = re.compile(r"(?<![\w.])(?<!android\.)R\.(\w+)\.(\w+)")
    found = []

    for kotlin in source_root.rglob("*.kt"):
        for number, line in enumerate(kotlin.read_text(errors="ignore").split("\n"), 1):
            if line.lstrip().startswith("//"):
                continue
            for kind, name in pattern.findall(line):
                found.append((kind, name, str(kotlin), number))

    return found


def main() -> int:
    root = pathlib.Path(sys.argv[1] if len(sys.argv) > 1 else ".")
    app = root / "android" / "app" / "src" / "main"
    res, source = app / "res", app / "java"

    if not res.is_dir():
        print(f"res/ bulunamadı: {res}", file=sys.stderr)
        return 2

    known = declared(res)
    kinds = {kind for kind, _ in known}
    problems = []
    checked = 0

    for kind, name, path, number in used(source):
        # Only kinds this project actually declares; `R.id` from a view
        # binding, say, is not something res/values can answer for.
        if kind not in kinds:
            continue

        checked += 1
        if (kind, name) not in known:
            problems.append(f"{path}:{number}  R.{kind}.{name} diye bir kaynak yok")

    for problem in sorted(problems):
        print(problem.replace(str(root) + "/", ""))

    print(f"{checked} R.* kullanımı denetlendi, {len(problems)} sorun.")
    return 1 if problems else 0


if __name__ == "__main__":
    sys.exit(main())
