import { strict as assert } from 'node:assert'
import { existsSync } from 'node:fs'
import { join } from 'node:path'
import { describe, it, before, after } from 'node:test'
import {
  ClusterStream,
  readAttachments,
  readMkvHeader,
  parseClusters,
  isAudioTrack,
  isSubtitleTrack,
  isVideoTrack,
  type MkvHeader,
  type MkvTrack,
  type RangeReader,
} from '../src/mkv/demuxer.ts'
import { MEDIA_DIR, fileRangeReader } from './helpers.ts'

const MKV = join(MEDIA_DIR, 'episode.mkv')
const MKV_OPUS = join(MEDIA_DIR, 'episode-opus.mkv')

// The corpus is generated by tools/make-test-media.sh and is gitignored, so a
// clean checkout skips these rather than failing.
const available = existsSync(MKV)

describe('Matroska demuxer', { skip: available ? false : 'run tools/make-test-media.sh first' }, () => {
  let read: RangeReader
  let size: number
  let close: () => Promise<void>
  let header: MkvHeader

  before(async () => {
    ;({ read, size, close } = await fileRangeReader(MKV))
    header = await readMkvHeader(read, size)
  })

  after(async () => close?.())

  it('identifies the container', () => {
    assert.equal(header.docType, 'matroska')
    assert.equal(header.timestampScale, 1_000_000)
    assert.ok(header.segmentStart > 0)
  })

  it('reads the duration from Info', () => {
    assert.ok(header.durationNs !== null)
    const seconds = header.durationNs! / 1e9
    assert.ok(seconds > 59 && seconds < 61, `expected ~60s, got ${seconds}`)
  })

  it('finds all three tracks with their codecs', () => {
    assert.equal(header.tracks.length, 3)

    const video = header.tracks.find(isVideoTrack)
    assert.ok(video, 'no video track')
    assert.equal(video.codecId, 'V_MPEG4/ISO/AVC')
    assert.equal(video.video?.pixelWidth, 1920)
    assert.equal(video.video?.pixelHeight, 1080)
    assert.ok(video.codecPrivate && video.codecPrivate.length > 0, 'missing avcC')

    const audio = header.tracks.find(isAudioTrack)
    assert.ok(audio, 'no audio track')
    assert.equal(audio.codecId, 'A_AAC')
    assert.equal(audio.audio?.samplingFrequency, 48000)
    assert.equal(audio.audio?.channels, 2)
    assert.equal(audio.language, 'jpn')

    const subtitle = header.tracks.find(isSubtitleTrack)
    assert.ok(subtitle, 'no subtitle track')
    assert.equal(subtitle.codecId, 'S_TEXT/ASS')
    assert.equal(subtitle.language, 'tur')
    // The ASS header (Script Info + V4+ Styles) rides in CodecPrivate.
    const codecPrivate = new TextDecoder().decode(subtitle.codecPrivate!)
    assert.match(codecPrivate, /\[Script Info\]/)
    assert.match(codecPrivate, /\[V4\+ Styles\]/)
  })

  it('builds a seek index from Cues', () => {
    assert.ok(header.cues.length > 5, `expected several cues, got ${header.cues.length}`)
    // Cues must be sorted and point somewhere sane inside the file.
    for (let i = 1; i < header.cues.length; i++) {
      assert.ok(header.cues[i]!.timeNs >= header.cues[i - 1]!.timeNs, 'cues out of order')
    }
    assert.ok(header.cues[0]!.clusterPosition >= header.segmentStart)
    assert.ok(header.cues.at(-1)!.clusterPosition < size)
  })

  it('extracts attached fonts', async () => {
    const attachments = await readAttachments(header, read, size)
    assert.equal(attachments.length, 3)
    const names = attachments.map((a) => a.filename).sort()
    assert.deepEqual(names, ['DejaVuSans.ttf', 'DejaVuSansMono.ttf', 'DejaVuSerif.ttf'])
    for (const font of attachments) {
      assert.match(font.mimeType, /font|octet-stream/)
      // Every TrueType file starts with the 0x00010000 sfnt version tag.
      assert.deepEqual([...font.data.subarray(0, 4)], [0x00, 0x01, 0x00, 0x00])
    }
  })

  it('parses frames out of the first clusters', async () => {
    const start = header.firstClusterOffset ?? header.cues[0]!.clusterPosition
    const bytes = await read(start, start + 2 * 1024 * 1024)
    const tracks = new Map<number, MkvTrack>(header.tracks.map((t) => [t.number, t]))

    const result = parseClusters(bytes, start, header.timestampScale, tracks)
    assert.ok(result.frames.length > 100, `expected many frames, got ${result.frames.length}`)
    assert.ok(result.consumed > 0)

    const videoTrack = header.tracks.find(isVideoTrack)!
    const videoFrames = result.frames.filter((f) => f.track === videoTrack.number)
    assert.ok(videoFrames.length > 20)

    // The very first video frame of the file must be a keyframe, or MSE has
    // nothing to start decoding from.
    assert.equal(videoFrames[0]!.keyframe, true)
    assert.ok(videoFrames[0]!.timestampNs < 100_000_000, 'first frame should be near zero')

    // Timestamps must advance; frames arrive in storage order which for AVC
    // with B-frames is decode order, so compare against the running maximum.
    let maxTs = -1
    for (const frame of videoFrames) {
      assert.ok(frame.data.length > 0, 'empty frame payload')
      maxTs = Math.max(maxTs, frame.timestampNs)
    }
    assert.ok(maxTs > 0)

    const audioTrack = header.tracks.find(isAudioTrack)!
    const audioFrames = result.frames.filter((f) => f.track === audioTrack.number)
    assert.ok(audioFrames.length > 20, 'expected audio frames')

    const subtitleTrack = header.tracks.find(isSubtitleTrack)!
    const subtitleFrames = result.frames.filter((f) => f.track === subtitleTrack.number)
    assert.ok(subtitleFrames.length > 0, 'expected subtitle blocks')
    // ASS blocks carry the Dialogue fields after ReadOrder, comma-separated.
    const text = new TextDecoder().decode(subtitleFrames[0]!.data)
    assert.match(text, /Animeh player test/)
  })

  it('locates the first cluster even when it sits past the probe window', () => {
    assert.ok(header.firstClusterOffset !== null, 'no first cluster offset')
    assert.ok(header.firstClusterOffset! > header.segmentStart)
    assert.ok(header.firstClusterOffset! < size)
  })

  it('emits frames from a partial cluster instead of waiting for the whole one', async () => {
    const start = header.firstClusterOffset!
    const tracks = new Map<number, MkvTrack>(header.tracks.map((t) => [t.number, t]))
    const stream = new ClusterStream(tracks, header.timestampScale)

    // 300 KB lands well inside ffmpeg's multi-megabyte first cluster. The whole
    // point of the incremental reader is that this still produces frames.
    const window = 300_000
    const short = await read(start, start + window)
    const first = stream.push(short, start)

    assert.ok(first.needMore, 'expected the parser to ask for more bytes')
    assert.ok(first.frames.length > 0, 'a partial cluster must still yield frames')
    assert.ok(stream.insideCluster, 'stream should still be positioned inside the cluster')
    assert.ok(first.consumed > 0 && first.consumed <= short.length)

    // Continuing from `consumed` must pick up where the first window stopped,
    // with no gap and no repeats.
    const resumeAt = start + first.consumed
    const rest = await read(resumeAt, resumeAt + window)
    const second = stream.push(rest, resumeAt)
    assert.ok(second.frames.length > 0)

    const lastOfFirst = first.frames.at(-1)!
    const firstOfSecond = second.frames[0]!
    assert.ok(
      firstOfSecond.timestampNs >= lastOfFirst.timestampNs - 200_000_000,
      `frames should continue (${lastOfFirst.timestampNs} -> ${firstOfSecond.timestampNs})`,
    )

    // And the combined stream must stay monotonic overall.
    const all = [...first.frames, ...second.frames].filter((f) => f.track === tracks.get(f.track)?.number)
    assert.ok(all.length > first.frames.length)
  })

  it('reaches the same frames whether fed in one window or many', async () => {
    const start = header.firstClusterOffset!
    const tracks = new Map<number, MkvTrack>(header.tracks.map((t) => [t.number, t]))
    const total = 1_500_000
    const whole = await read(start, start + total)

    const oneShot = new ClusterStream(tracks, header.timestampScale).push(whole, start)

    // Same bytes, dribbled in 64 KB at a time with the leftover carried forward.
    const chunked = new ClusterStream(tracks, header.timestampScale)
    const frames: { track: number; timestampNs: number; size: number }[] = []
    let pending = new Uint8Array(0)
    let base = start
    for (let offset = 0; offset < total; offset += 64 * 1024) {
      const next = whole.subarray(offset, Math.min(offset + 64 * 1024, total))
      const merged = new Uint8Array(pending.length + next.length)
      merged.set(pending)
      merged.set(next, pending.length)
      const result = chunked.push(merged, base)
      for (const f of result.frames) {
        frames.push({ track: f.track, timestampNs: f.timestampNs, size: f.data.length })
      }
      pending = merged.subarray(result.consumed)
      base += result.consumed
    }

    assert.equal(frames.length, oneShot.frames.length, 'chunked feed lost or duplicated frames')
    for (let i = 0; i < frames.length; i++) {
      assert.equal(frames[i]!.track, oneShot.frames[i]!.track)
      assert.equal(frames[i]!.timestampNs, oneShot.frames[i]!.timestampNs)
      assert.equal(frames[i]!.size, oneShot.frames[i]!.data.length)
    }
  })
})

describe('Matroska demuxer — Opus variant', { skip: existsSync(MKV_OPUS) ? false : 'no corpus' }, () => {
  it('reads Opus track metadata and its OpusHead private data', async () => {
    const { read, size, close } = await fileRangeReader(MKV_OPUS)
    try {
      const header = await readMkvHeader(read, size)
      const audio = header.tracks.find(isAudioTrack)
      assert.ok(audio)
      assert.equal(audio.codecId, 'A_OPUS')
      assert.ok(audio.codecPrivate, 'Opus needs CodecPrivate')
      // CodecPrivate for Opus is the OpusHead identification header.
      assert.equal(new TextDecoder().decode(audio.codecPrivate!.subarray(0, 8)), 'OpusHead')
      // Opus always decodes at 48 kHz regardless of the original rate.
      assert.equal(audio.audio?.samplingFrequency, 48000)
      assert.ok(audio.codecDelayNs > 0, 'Opus tracks carry a CodecDelay')
    } finally {
      await close()
    }
  })
})
